version: 2.1

orbs:
  codacy: codacy/base@11.2.0
  codacy_plugins_test: codacy/plugins-test@2.0.11
workflows:
  version: 2
  compile_test_deploy:
    jobs:
      - codacy/checkout_and_version:
          write_sbt_version: true
      - codacy/sbt:
          name: checkfmt_and_compile
          cmd: sbt scalafmt::test test:scalafmt::test sbt:scalafmt::test +test:compile
          persist_to_workspace: true
          requires:
            - codacy/checkout_and_version
      - codacy/sbt:
          name: publish_docker_local
          cmd: |
            docker build --no-cache -f Dockerfile.base -t codacy-cppcheck-base:latest .
            sbt doc-generator/run
            sbt stage
            docker build --no-cache -t $CIRCLE_PROJECT_REPONAME:latest .
            docker save --output docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
          persist_to_workspace: true
          requires:
            - checkfmt_and_compile
      - codacy_plugins_test/run:
          name: plugins_test
          run_multiple_tests: true
          requires:
            - publish_docker_local
      - codacy/publish_docker:
          context: CodacyDocker
          requires:
            - plugins_test
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - codacy/publish_docker
